### ISSUE TITLE
EMC production stops while offline on server.

### ISSUE THREAD

**Issue by Naxanria** [LatvianModder/Project-EX#17] opened 2019-03-20 11:59 UTC
Chunkloading makes no difference, the EMC production stops while user is offline.

https://github.com/FTBTeam/FTB-Sky-Odyssey/issues/90

**Comment by zhykzhykzhyk** [comment] 2019-03-21 10:12
Duplicate of #9?

**Comment by cf-Botan** [comment] 2019-03-21 18:48
I could trace the problem and have found that knowledgeProvider.setEmc() reacts different if the player is offline. Example:

Project-EX/src/main/java/com/latmod/mods/projectex/tile/TilePowerFlower.java Line 47
As long as the player is online this function works like you would assume.  But if the player is offline the new EMC Value isn't set at all.
My work arount to this is to use an internal storage of the emc and add this value as soon as the player goes online. I've attached my "solution". Maybe someone with more knowledge has a better idea.

[TileLink-java-and-TilePowerFlower-java.zip](https://github.com/LatvianModder/Project-EX/files/2993537/TileLink-java-and-TilePowerFlower-java.zip)

**Comment by LatvianModder** [comment] 2019-03-22 01:34
I have worked out a solution for this already and next update will fix this. I basically have my own map of player data and it allows to modify that and saves when world saves.

**Comment by cf-Botan** [comment] 2019-03-23 16:41
As of ProjectEX-1.1.0.18 the multiplayer emc generation works fine. However no emc generation in singleplayer.

**Closed** 2019-03-23 20:15 UTC
Labels: bug
